export const DAYOVA_DESIGN_SYSTEM = {
	brand: {
		attributes: ["structured", "clear", "trustworthy", "supportive", "calm"],
		direction:
			"Modern EdTech look with solid colors, bold systems, quiet hierarchy, and at most one gradient per view.",
	},
	colors: {
		primary: "#00BAFF",
		primaryStrong: "#00A0E6",
		primaryAccent: "#4FD8FF",
		primaryForeground: "#FFFFFF",
		buttonNeutral: "#1A1A1A",
		buttonNeutralForeground: "#FFFFFF",
		secondary: "#AF52DE",
		text: "#1A1A1A",
		textMuted: "#697586",
		background: "#F6F6F4",
		appBackground: "#F6F6F4",
		surface: "#FFFFFF",
		light2: "#F3F6FA",
		light3: "#FAFAFC",
		mutedSurface: "#F3F6FA",
		border: "#DCE6EE",
		success: "#34C759",
		successSubtle: "#E8F9EE",
		wrong: "#FF9500",
		wrongSubtle: "#FFF2DE",
		warning: "#FF9500",
		warningSubtle: "#FFF2DE",
		destructive: "#FF3B30",
		info: "#C9A100",
		infoSubtle: "#FFF7CC",
		system: "#00BAFF",
		systemSubtle: "#EAF8FF",
		theorie: "#5856D6",
		theorieSubtle: "#EFEFFF",
		ueben: "#AF52DE",
		uebenSubtle: "#F6EAFE",
		praxis: "#00C7BE",
		praxisSubtle: "#E6FAF8",
		path1: "#D7DCE3",
		path2: "#D7DCE3",
		path3: "#8A8D92",
		path4: "#697586",
		path5: "#00A0E6",
		path6: "#00BAFF",
		path7: "#4FD8FF",
	},
	gradients: {
		primaryInteractive: {
			colors: ["#00A0E6", "#4FD8FF"],
			start: { x: 0, y: 0.5 },
			end: { x: 1, y: 0.5 },
		},
	},
	elevation: {
		// Native shadow/elevation is still expressed as style objects in the few
		// places that need cross-platform depth beyond NativeWind's preset shadows.
		surface: {
			shadowColor: "#000000",
			shadowOpacity: 0.06,
			shadowRadius: 12,
			shadowOffset: { width: 0, height: 4 },
			elevation: 3,
		},
		soft: {
			shadowColor: "#000000",
			shadowOpacity: 0.05,
			shadowRadius: 8,
			shadowOffset: { width: 0, height: 4 },
			elevation: 2,
		},
	},
	typography: {
		fontFamily: "Poppins",
		headline: {
			h1: { fontSize: 32, lineHeight: 48, fontWeight: "600" },
			h2: { fontSize: 24, lineHeight: 36, fontWeight: "600" },
		},
		body: {
			xl: { fontSize: 20, lineHeight: 30, fontWeight: "400" },
			xlSemibold: { fontSize: 20, lineHeight: 30, fontWeight: "600" },
			lg: { fontSize: 16, lineHeight: 24, fontWeight: "400" },
			lgSemibold: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
			md: { fontSize: 14, lineHeight: 21, fontWeight: "400" },
			mdSemibold: { fontSize: 14, lineHeight: 21, fontWeight: "600" },
			sm: { fontSize: 12, lineHeight: 18, fontWeight: "400" },
			smSemibold: { fontSize: 12, lineHeight: 18, fontWeight: "600" },
			xs: { fontSize: 10, lineHeight: 15, fontWeight: "400" },
			xsSemibold: { fontSize: 10, lineHeight: 15, fontWeight: "600" },
		},
		button: {
			default: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
			small: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
		},
		field: {
			placeholder: { fontSize: 16, lineHeight: 24 },
			label: { fontSize: 12, lineHeight: 18 },
			description: { fontSize: 12, lineHeight: 18 },
		},
	},
	radius: {
		inner: 64,
		outer: 96,
		button: 32,
		input: 28,
	},
	size: {
		button: {
			borderWidth: 0.3,
			defaultHeight: 56,
		},
	},
} as const;
