// Stable identifiers only: never derive analytics names from UI text or user data.
export const FEATURE_INTERACTIONS = [
	"home.day_selected",
	"home.entry_opened",
	"home.create_opened",
	"home.create_exam_selected",
	"home.create_homework_selected",
	"settings.profile_opened",
	"settings.learning_times_opened",
	"settings.timetable_opened",
	"settings.notifications_opened",
	"settings.release_information_opened",
	"settings.subscription_opened",
	"settings.support_opened",
	"settings.ai_privacy_opened",
	"settings.privacy_opened",
	"settings.terms_opened",
	"settings.theme_changed",
	"settings.notification_changed",
	"settings.profile_saved",
	"timetable.lesson_added",
	"timetable.lesson_removed",
	"timetable.day_selected",
	"timetable.import",
	"timetable.save",
	"learning_times.save",
	"learning_times.remove",
	"homework.create",
	"homework.complete",
	"homework.reopen",
	"homework.remove",
	"exam.create",
	"exam.update",
	"exam.remove",
	"entry.step_changed",
	"entry.complete",
	"entry.reopen",
	"learning_plan.content_viewed",
	"learning_plan.accept",
	"learning_plan.scope_confirm",
	"material.remove",
	"learning_plan.session_selected",
	"learning_session.answer",
	"learning_session.answer_unknown",
	"learning_session.question_repeated",
	"learning_session.theory_next",
	"learning_session.theory_previous",
	"learning_session.continue",
	"learning_session.retry",
	"learning_session.reschedule",
	"learning_session.remove",
	"analysis.exam_selected",
	"analysis.topic_opened",
	"analysis.answer_revealed",
	"trial.start",
	"paywall.subscription_opened",
	"subscription.checkout",
	"subscription.restore",
	"subscription.plan_selected",
] as const;
export type FeatureInteraction = (typeof FEATURE_INTERACTIONS)[number];
export const INTERACTION_OUTCOMES = [
	"performed",
	"attempted",
	"succeeded",
	"failed",
	"cancelled",
	"pending",
] as const;
export type InteractionOutcome = (typeof INTERACTION_OUTCOMES)[number];

// Match Expo route templates, never pathnames, search params, names or content.
export const ANALYTICS_SCREENS = {
	home: "home",
	settings: "settings",
	analyse: "analysis",
	"learning-plans": "learning_plans",
	timetable: "timetable",
	"learning-times": "learning_times",
	"learning-times/edit": "learning_time_editor",
	profile: "profile",
	"notification-settings": "notification_settings",
	notifications: "notifications",
	"entry/new": "entry_creation",
	"entry/[id]": "entry_detail",
	"entry/success": "entry_success",
	"learning-plans/new": "plan_creation",
	"learning-plans/[planId]": "plan_detail",
	"learning-plans/[planId]/review": "plan_review",
	"learning-plans/[planId]/scope": "plan_scope",
	"learning-plans/[planId]/workload": "plan_workload",
	"learning-plans/[planId]/analysis": "plan_setup_analysis",
	"learning-plans/[planId]/generating": "plan_generating",
	"learning-plans/[planId]/success": "plan_success",
	"learning-plans/[planId]/sessions/[sessionId]": "learning_session",
	"learning-plans/[planId]/sessions/[sessionId]/edit": "session_editor",
	"analyse/wissensstand": "analysis_knowledge",
	"analyse/lernhuerde": "analysis_obstacle",
	"analyse/naechster-schritt": "analysis_next_step",
	"analyse/development": "analysis_history",
	paywall: "paywall",
	subscription: "subscription",
	"subscription-success": "subscription_success",
	trial: "trial",
	"onboarding/[step]": "onboarding",
	"onboarding/creating": "onboarding_creating",
} as const;
export type AnalyticsScreen =
	(typeof ANALYTICS_SCREENS)[keyof typeof ANALYTICS_SCREENS];
export function analyticsScreenForSegments(
	segments: readonly string[],
): AnalyticsScreen | undefined {
	const route = segments
		.filter((segment) => !segment.startsWith("(") && segment !== "index")
		.join("/");
	return Object.hasOwn(ANALYTICS_SCREENS, route)
		? ANALYTICS_SCREENS[route as keyof typeof ANALYTICS_SCREENS]
		: undefined;
}

export const INTERACTION_VALUES = [
	"annual",
	"monthly",
	"basics",
	"planning",
	"learningAvailability",
	"examType",
	"examDetails",
	"systemNotificationsEnabled",
	"dailyBriefingEnabled",
	"dailyBriefingTime",
	"beforeExamEnabled",
	"beforeLearningTimeEnabled",
	"beforeHomeworkWorkEnabled",
	"beforeHomeworkDueEnabled",
	"reminderOffsetMinutes",
	"forgottenEventEnabled",
] as const;
export type InteractionValue = (typeof INTERACTION_VALUES)[number];
