const GERMAN_UI_REPLACEMENTS: ReadonlyArray<[RegExp, string]> = [
	[/\bMuendliche\b/g, "Mündliche"],
	[/\bmuendliche\b/g, "mündliche"],
	[/\bFuer\b/g, "Für"],
	[/\bfuer\b/g, "für"],
	[/\bGeraet\b/g, "Gerät"],
	[/\bgeraet\b/g, "gerät"],
	[/\bGeraete\b/g, "Geräte"],
	[/\bgeraete\b/g, "geräte"],
	[/\bgroesste\b/g, "größte"],
	[/\bGroesste\b/g, "Größte"],
	[/\bgroessten\b/g, "größten"],
	[/\bGroessten\b/g, "Größten"],
	[/\bGross\b/g, "Groß"],
	[/\bgross\b/g, "groß"],
	[/\bPruefung\b/g, "Prüfung"],
	[/\bpruefung\b/g, "prüfung"],
	[/\bPruefungen\b/g, "Prüfungen"],
	[/\bpruefungen\b/g, "prüfungen"],
	[/\bPruefungsart\b/g, "Prüfungsart"],
	[/\bpruefungsart\b/g, "prüfungsart"],
	[/\bPruefungstag\b/g, "Prüfungstag"],
	[/\bpruefungstag\b/g, "prüfungstag"],
	[/\bSchueler\b/g, "Schüler"],
	[/\bschueler\b/g, "schüler"],
	[/\bStrasse\b/g, "Straße"],
	[/\bstrasse\b/g, "straße"],
	[/\bAbschlusspruefung\b/g, "Abschlussprüfung"],
	[/\babschlusspruefung\b/g, "abschlussprüfung"],
	[/\bUebung\b/g, "Übung"],
	[/\buebung\b/g, "übung"],
	[/\bUebungen\b/g, "Übungen"],
	[/\buebungen\b/g, "übungen"],
	[/\bUeben\b/g, "Üben"],
	[/\bueben\b/g, "üben"],
	[/\bWeiss\b/g, "Weiß"],
	[/\bweiss\b/g, "weiß"],
];

export const formatGermanUiText = (value: string) =>
	GERMAN_UI_REPLACEMENTS.reduce(
		(formatted, [pattern, replacement]) =>
			formatted.replace(pattern, replacement),
		value,
	);
