const REVENUECAT_REDEMPTION_SCHEME_PATTERN = /^rc-[a-z0-9]+$/;

export const getRevenueCatRedemptionScheme = (
	value: string | undefined,
	{ required = false }: { required?: boolean } = {},
) => {
	const scheme = value?.trim().toLowerCase().replace(/:$/, "");

	if (!scheme) {
		if (required) {
			throw new Error(
				"REVENUECAT_REDEMPTION_SCHEME is required for release builds. Copy the custom rc-… scheme from the RevenueCat web config into the EAS environment.",
			);
		}
		return null;
	}

	if (!REVENUECAT_REDEMPTION_SCHEME_PATTERN.test(scheme)) {
		throw new Error(
			"REVENUECAT_REDEMPTION_SCHEME must match the rc-… scheme generated by RevenueCat.",
		);
	}

	return scheme;
};
