allowBuilds:
  esbuild: true
  "@clerk/shared": false
  browser-tabs-lock: false
  bufferutil: false
  core-js: false
  dtrace-provider: false
  msgpackr-extract: false
  tesseract.js: false
  utf-8-validate: false

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  '@expo/metro-config@56.0.17': patches/@expo__metro-config@56.0.17.patch
  nativewind@4.2.3: patches/nativewind@4.2.3.patch
  oxc-parser@0.130.0: patches/oxc-parser@0.130.0.patch
