allowBuilds:
  '@clerk/shared': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  utf-8-validate: true
patchedDependencies:
  expo-keep-awake@15.0.8: patches/expo-keep-awake@15.0.8.patch
