/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./App.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          100: "hsl(var(--primary-100))",
          90: "hsl(var(--primary-90))",
          80: "hsl(var(--primary-80))",
          70: "hsl(var(--primary-70))",
          60: "hsl(var(--primary-60))",
          50: "hsl(var(--primary-50))",
          40: "hsl(var(--primary-40))",
          30: "hsl(var(--primary-30))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          100: "hsl(var(--secondary-100))",
          90: "hsl(var(--secondary-90))",
          80: "hsl(var(--secondary-80))",
          70: "hsl(var(--secondary-70))",
          60: "hsl(var(--secondary-60))",
          50: "hsl(var(--secondary-50))",
          40: "hsl(var(--secondary-40))",
          30: "hsl(var(--secondary-30))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        text: "hsl(var(--foreground))",
        bg: "hsl(var(--background))",
        black: {
          DEFAULT: "hsl(var(--black-100))",
          100: "hsl(var(--black-100))",
          90: "hsl(var(--black-90))",
          80: "hsl(var(--black-80))",
          70: "hsl(var(--black-70))",
          60: "hsl(var(--black-60))",
          50: "hsl(var(--black-50))",
          40: "hsl(var(--black-40))",
          30: "hsl(var(--black-30))",
          20: "hsl(var(--black-20))",
          10: "hsl(var(--black-10))",
        },
        white: {
          DEFAULT: "hsl(var(--white-100))",
          100: "hsl(var(--white-100))",
          90: "hsl(var(--white-90))",
          80: "hsl(var(--white-80))",
          70: "hsl(var(--white-70))",
          60: "hsl(var(--white-60))",
          50: "hsl(var(--white-50))",
          40: "hsl(var(--white-40))",
          30: "hsl(var(--white-30))",
          20: "hsl(var(--white-20))",
          10: "hsl(var(--white-10))",
        },
      },
      fontFamily: {
        poppins: ["Poppins-Regular", "Poppins"],
        dmsans: ["DMSans-Regular", "DM Sans"],
        inter: ["Inter-Regular", "Inter"],
      },
      fontSize: {
        '12': ['12px', { lineHeight: '16px' }],
        '14': ['14px', { lineHeight: '20px' }],
        '16': ['16px', { lineHeight: '24px' }],
        '18': ['18px', { lineHeight: '25.2px' }],
        '20': ['20px', { lineHeight: '24px' }],
        '24': ['24px', { lineHeight: '32px' }],
        '32': ['32px', { lineHeight: '40px' }],
        '40': ['40px', { lineHeight: '48px' }],
        '56': ['56px', { lineHeight: '64px' }],
        '64': ['64px', { lineHeight: '72px' }],
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '24': '24px',
        '32': '32px',
        '36': '36px',
        '40': '40px',
        '48': '48px',
        '56': '56px',
        '64': '64px',
        '80': '80px',
        '120': '120px',
        '200': '200px',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'card': '32px',
        'button': '24px',
        'input': '30px',
        'tab': '30px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
};
