import AlertCircleIcon from "@hugeicons/core-free-icons/AlertCircleIcon";
import ArrowDown01Icon from "@hugeicons/core-free-icons/ArrowDown01Icon";
import ArrowLeft01Icon from "@hugeicons/core-free-icons/ArrowLeft01Icon";
import ArrowRight01Icon from "@hugeicons/core-free-icons/ArrowRight01Icon";
import ArrowUpRight01Icon from "@hugeicons/core-free-icons/ArrowUpRight01Icon";
import Atom02Icon from "@hugeicons/core-free-icons/Atom02Icon";
import Attachment01Icon from "@hugeicons/core-free-icons/Attachment01Icon";
import Backpack03Icon from "@hugeicons/core-free-icons/Backpack03Icon";
import BookOpen01Icon from "@hugeicons/core-free-icons/BookOpen01Icon";
import BulbIcon from "@hugeicons/core-free-icons/BulbIcon";
import Calculator01Icon from "@hugeicons/core-free-icons/Calculator01Icon";
import Calendar03Icon from "@hugeicons/core-free-icons/Calendar03Icon";
import Cancel01Icon from "@hugeicons/core-free-icons/Cancel01Icon";
import Chemistry01Icon from "@hugeicons/core-free-icons/Chemistry01Icon";
import Clock03Icon from "@hugeicons/core-free-icons/Clock03Icon";
import CodeIcon from "@hugeicons/core-free-icons/CodeIcon";
import ComputerIcon from "@hugeicons/core-free-icons/ComputerIcon";
import Delete02Icon from "@hugeicons/core-free-icons/Delete02Icon";
import Dna01Icon from "@hugeicons/core-free-icons/Dna01Icon";
import Dumbbell02Icon from "@hugeicons/core-free-icons/Dumbbell02Icon";
import EarthIcon from "@hugeicons/core-free-icons/EarthIcon";
import Fire02Icon from "@hugeicons/core-free-icons/Fire02Icon";
import FootballIcon from "@hugeicons/core-free-icons/FootballIcon";
import GlobeIcon from "@hugeicons/core-free-icons/GlobeIcon";
import GreekHelmetIcon from "@hugeicons/core-free-icons/GreekHelmetIcon";
import Home02Icon from "@hugeicons/core-free-icons/Home02Icon";
import InformationCircleIcon from "@hugeicons/core-free-icons/InformationCircleIcon";
import LanguageCircleIcon from "@hugeicons/core-free-icons/LanguageCircleIcon";
import Logout03Icon from "@hugeicons/core-free-icons/Logout03Icon";
import Mail01Icon from "@hugeicons/core-free-icons/Mail01Icon";
import MapsCircle01Icon from "@hugeicons/core-free-icons/MapsCircle01Icon";
import Mic01Icon from "@hugeicons/core-free-icons/Mic01Icon";
import Moon02Icon from "@hugeicons/core-free-icons/Moon02Icon";
import Mortarboard01Icon from "@hugeicons/core-free-icons/Mortarboard01Icon";
import MusicNote01Icon from "@hugeicons/core-free-icons/MusicNote01Icon";
import NotebookIcon from "@hugeicons/core-free-icons/NotebookIcon";
import NoteIcon from "@hugeicons/core-free-icons/NoteIcon";
import Notification01Icon from "@hugeicons/core-free-icons/Notification01Icon";
import NotificationOff03Icon from "@hugeicons/core-free-icons/NotificationOff03Icon";
import PaintBoardIcon from "@hugeicons/core-free-icons/PaintBoardIcon";
import PaintBrush01Icon from "@hugeicons/core-free-icons/PaintBrush01Icon";
import PencilIcon from "@hugeicons/core-free-icons/PencilIcon";
import Plant04Icon from "@hugeicons/core-free-icons/Plant04Icon";
import PlusSignIcon from "@hugeicons/core-free-icons/PlusSignIcon";
import PropertyEditIcon from "@hugeicons/core-free-icons/PropertyEditIcon";
import Rocket01Icon from "@hugeicons/core-free-icons/Rocket01Icon";
import Route02Icon from "@hugeicons/core-free-icons/Route02Icon";
import ScanImageIcon from "@hugeicons/core-free-icons/ScanImageIcon";
import Settings01Icon from "@hugeicons/core-free-icons/Settings01Icon";
import SparklesIcon from "@hugeicons/core-free-icons/SparklesIcon";
import SquareLock02Icon from "@hugeicons/core-free-icons/SquareLock02Icon";
import SquareRootSquareIcon from "@hugeicons/core-free-icons/SquareRootSquareIcon";
import Sun01Icon from "@hugeicons/core-free-icons/Sun01Icon";
import Task01Icon from "@hugeicons/core-free-icons/Task01Icon";
import TaskEdit01Icon from "@hugeicons/core-free-icons/TaskEdit01Icon";
import Telescope01Icon from "@hugeicons/core-free-icons/Telescope01Icon";
import Tick02Icon from "@hugeicons/core-free-icons/Tick02Icon";
import Time04Icon from "@hugeicons/core-free-icons/Time04Icon";
import TimeManagementCircleIcon from "@hugeicons/core-free-icons/TimeManagementCircleIcon";
import UserCircleIcon from "@hugeicons/core-free-icons/UserCircleIcon";
import ViewIcon from "@hugeicons/core-free-icons/ViewIcon";
import ViewOffIcon from "@hugeicons/core-free-icons/ViewOffIcon";
import { HugeiconsIcon, type HugeiconsProps } from "@hugeicons/react-native";

type IconProps = Omit<HugeiconsProps, "icon">;

const createIcon = (icon: HugeiconsProps["icon"]) => (props: IconProps) => (
	<HugeiconsIcon icon={icon} {...props} />
);

export const Attachment = createIcon(Attachment01Icon);
export const Atom = createIcon(Atom02Icon);
export const ArrowLeft = createIcon(ArrowLeft01Icon);
export const ArrowRight = createIcon(ArrowRight01Icon);
export const ArrowUpRight = createIcon(ArrowUpRight01Icon);
export const Backpack = createIcon(Backpack03Icon);
export const Bell = createIcon(Notification01Icon);
export const BellOff = createIcon(NotificationOff03Icon);
export const BookOpen = createIcon(BookOpen01Icon);
export const Bulb = createIcon(BulbIcon);
export const CalendarDays = createIcon(Calendar03Icon);
export const Calculator = createIcon(Calculator01Icon);
export const Check = createIcon(Tick02Icon);
export const Chemistry = createIcon(Chemistry01Icon);
export const ChevronDown = createIcon(ArrowDown01Icon);
export const CircleAlert = createIcon(AlertCircleIcon);
export const ClipboardList = createIcon(Task01Icon);
export const ClipboardEdit = createIcon(TaskEdit01Icon);
export const Clock3 = createIcon(Clock03Icon);
export const Code = createIcon(CodeIcon);
export const Computer = createIcon(ComputerIcon);
export const Dna = createIcon(Dna01Icon);
export const Dumbbell = createIcon(Dumbbell02Icon);
export const Earth = createIcon(EarthIcon);
export const Eye = createIcon(ViewIcon);
export const EyeOff = createIcon(ViewOffIcon);
export const Fire = createIcon(Fire02Icon);
export const Football = createIcon(FootballIcon);
export const GraduationCap = createIcon(Mortarboard01Icon);
export const GreekHelmet = createIcon(GreekHelmetIcon);
export const Globe = createIcon(GlobeIcon);
export const Home = createIcon(Home02Icon);
export const Info = createIcon(InformationCircleIcon);
export const Language = createIcon(LanguageCircleIcon);
export const Logout = createIcon(Logout03Icon);
export const Maps = createIcon(MapsCircle01Icon);
export const Mail = createIcon(Mail01Icon);
export const Mic = createIcon(Mic01Icon);
export const Moon = createIcon(Moon02Icon);
export const MusicNote = createIcon(MusicNote01Icon);
export const Note = createIcon(NoteIcon);
export const NotebookPen = createIcon(NotebookIcon);
export const Palette = createIcon(PaintBoardIcon);
export const PaintBrush = createIcon(PaintBrush01Icon);
export const Pencil = createIcon(PencilIcon);
export const Plant = createIcon(Plant04Icon);
export const Plus = createIcon(PlusSignIcon);
export const PropertyEdit = createIcon(PropertyEditIcon);
export const Route2 = createIcon(Route02Icon);
export const Rocket = createIcon(Rocket01Icon);
export const ScanImage = createIcon(ScanImageIcon);
export const Settings = createIcon(Settings01Icon);
export const SquareLock = createIcon(SquareLock02Icon);
export const SquareRootSquare = createIcon(SquareRootSquareIcon);
export const Sparkles = createIcon(SparklesIcon);
export const Sun = createIcon(Sun01Icon);
export const Telescope = createIcon(Telescope01Icon);
export const Time04 = createIcon(Time04Icon);
export const TimeManagement = createIcon(TimeManagementCircleIcon);
export const Timer = createIcon(Clock03Icon);
export const Trash2 = createIcon(Delete02Icon);
export const UserRound = createIcon(UserCircleIcon);
export const X = createIcon(Cancel01Icon);
